steps:
  - name: python:3.14-slim
    id: Smoketests
    entrypoint: bash
    args:
      - -ceu
      - |
        # Fail on errors, showing commands attempted
        set -euxo pipefail

        echo 'Compiling all Python Files'
        python -m compileall . -q

        echo 'Creating .venv and installing dependencies'
        python -m venv .venv
        . .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

        echo 'Starting dev server'
        python app.py &
        server_pid=$!
        trap "kill $server_pid || true" EXIT

        echo 'Installing curl to test server; also allows it time to start'
        apt-get update > /dev/null
        apt-get install -y curl > /dev/null

        echo 'Making sure dev server responds with expected content'
        curl -sS http://localhost:8080 > /tmp/response.html
        if grep -q "and/or fork:" /tmp/response.html ; then
          echo "Smoke test passed: expected content found in response."
          exit 0
        fi

        echo 'Head and tail of bad response:'
        head /tmp/response.html
        tail /tmp/response.html

        echo 'Smoke test failed: dev server did not serve expected content.'
        exit 1
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PLATFORM: managed
  _TRIGGER_ID: d9e7f1b6-c92a-4d12-874f-084a4ad58809
  _SERVICE_NAME: waikikiwx
  _DEPLOY_REGION: us-west1
  _AR_HOSTNAME: us-west1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: virtual-indexer-344822
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - waikikiwx
